// Generated by gencpp from file movo_msgs/Dynamics.msg
// DO NOT EDIT!


#ifndef MOVO_MSGS_MESSAGE_DYNAMICS_H
#define MOVO_MSGS_MESSAGE_DYNAMICS_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace movo_msgs
{
template <class ContainerAllocator>
struct Dynamics_
{
  typedef Dynamics_<ContainerAllocator> Type;

  Dynamics_()
    : header()
    , x_vel_target_mps(0.0)
    , y_vel_target_mps(0.0)
    , yaw_rate_target_rps(0.0)
    , linear_actuator_target_m(0.0)
    , x_vel_limit_mps(0.0)
    , y_vel_limit_mps(0.0)
    , yaw_rate_limit_rps(0.0)
    , linear_actuator_vel_limit_mps(0.0)
    , wheel_vel_mps()
    , wheel_pos_m()
    , linear_actuator_vel_mps(0.0)
    , linear_actuator_position_m(0.0)
    , x_accel_mps2(0.0)
    , y_accel_mps2(0.0)
    , yaw_accel_mps2(0.0)
    , yaw_angle_rad(0.0)
    , odom_yaw_angle_rad(0.0)  {
    }
  Dynamics_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , x_vel_target_mps(0.0)
    , y_vel_target_mps(0.0)
    , yaw_rate_target_rps(0.0)
    , linear_actuator_target_m(0.0)
    , x_vel_limit_mps(0.0)
    , y_vel_limit_mps(0.0)
    , yaw_rate_limit_rps(0.0)
    , linear_actuator_vel_limit_mps(0.0)
    , wheel_vel_mps(_alloc)
    , wheel_pos_m(_alloc)
    , linear_actuator_vel_mps(0.0)
    , linear_actuator_position_m(0.0)
    , x_accel_mps2(0.0)
    , y_accel_mps2(0.0)
    , yaw_accel_mps2(0.0)
    , yaw_angle_rad(0.0)
    , odom_yaw_angle_rad(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef float _x_vel_target_mps_type;
  _x_vel_target_mps_type x_vel_target_mps;

   typedef float _y_vel_target_mps_type;
  _y_vel_target_mps_type y_vel_target_mps;

   typedef float _yaw_rate_target_rps_type;
  _yaw_rate_target_rps_type yaw_rate_target_rps;

   typedef float _linear_actuator_target_m_type;
  _linear_actuator_target_m_type linear_actuator_target_m;

   typedef float _x_vel_limit_mps_type;
  _x_vel_limit_mps_type x_vel_limit_mps;

   typedef float _y_vel_limit_mps_type;
  _y_vel_limit_mps_type y_vel_limit_mps;

   typedef float _yaw_rate_limit_rps_type;
  _yaw_rate_limit_rps_type yaw_rate_limit_rps;

   typedef float _linear_actuator_vel_limit_mps_type;
  _linear_actuator_vel_limit_mps_type linear_actuator_vel_limit_mps;

   typedef std::vector<float, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<float>> _wheel_vel_mps_type;
  _wheel_vel_mps_type wheel_vel_mps;

   typedef std::vector<float, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<float>> _wheel_pos_m_type;
  _wheel_pos_m_type wheel_pos_m;

   typedef float _linear_actuator_vel_mps_type;
  _linear_actuator_vel_mps_type linear_actuator_vel_mps;

   typedef float _linear_actuator_position_m_type;
  _linear_actuator_position_m_type linear_actuator_position_m;

   typedef float _x_accel_mps2_type;
  _x_accel_mps2_type x_accel_mps2;

   typedef float _y_accel_mps2_type;
  _y_accel_mps2_type y_accel_mps2;

   typedef float _yaw_accel_mps2_type;
  _yaw_accel_mps2_type yaw_accel_mps2;

   typedef float _yaw_angle_rad_type;
  _yaw_angle_rad_type yaw_angle_rad;

   typedef float _odom_yaw_angle_rad_type;
  _odom_yaw_angle_rad_type odom_yaw_angle_rad;





  typedef boost::shared_ptr< ::movo_msgs::Dynamics_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::movo_msgs::Dynamics_<ContainerAllocator> const> ConstPtr;

}; // struct Dynamics_

typedef ::movo_msgs::Dynamics_<std::allocator<void> > Dynamics;

typedef boost::shared_ptr< ::movo_msgs::Dynamics > DynamicsPtr;
typedef boost::shared_ptr< ::movo_msgs::Dynamics const> DynamicsConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::movo_msgs::Dynamics_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::movo_msgs::Dynamics_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::movo_msgs::Dynamics_<ContainerAllocator1> & lhs, const ::movo_msgs::Dynamics_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.x_vel_target_mps == rhs.x_vel_target_mps &&
    lhs.y_vel_target_mps == rhs.y_vel_target_mps &&
    lhs.yaw_rate_target_rps == rhs.yaw_rate_target_rps &&
    lhs.linear_actuator_target_m == rhs.linear_actuator_target_m &&
    lhs.x_vel_limit_mps == rhs.x_vel_limit_mps &&
    lhs.y_vel_limit_mps == rhs.y_vel_limit_mps &&
    lhs.yaw_rate_limit_rps == rhs.yaw_rate_limit_rps &&
    lhs.linear_actuator_vel_limit_mps == rhs.linear_actuator_vel_limit_mps &&
    lhs.wheel_vel_mps == rhs.wheel_vel_mps &&
    lhs.wheel_pos_m == rhs.wheel_pos_m &&
    lhs.linear_actuator_vel_mps == rhs.linear_actuator_vel_mps &&
    lhs.linear_actuator_position_m == rhs.linear_actuator_position_m &&
    lhs.x_accel_mps2 == rhs.x_accel_mps2 &&
    lhs.y_accel_mps2 == rhs.y_accel_mps2 &&
    lhs.yaw_accel_mps2 == rhs.yaw_accel_mps2 &&
    lhs.yaw_angle_rad == rhs.yaw_angle_rad &&
    lhs.odom_yaw_angle_rad == rhs.odom_yaw_angle_rad;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::movo_msgs::Dynamics_<ContainerAllocator1> & lhs, const ::movo_msgs::Dynamics_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace movo_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::movo_msgs::Dynamics_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::movo_msgs::Dynamics_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::movo_msgs::Dynamics_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::movo_msgs::Dynamics_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::movo_msgs::Dynamics_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::movo_msgs::Dynamics_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::movo_msgs::Dynamics_<ContainerAllocator> >
{
  static const char* value()
  {
    return "dd32431766932850de2062a4263871b4";
  }

  static const char* value(const ::movo_msgs::Dynamics_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xdd32431766932850ULL;
  static const uint64_t static_value2 = 0xde2062a4263871b4ULL;
};

template<class ContainerAllocator>
struct DataType< ::movo_msgs::Dynamics_<ContainerAllocator> >
{
  static const char* value()
  {
    return "movo_msgs/Dynamics";
  }

  static const char* value(const ::movo_msgs::Dynamics_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::movo_msgs::Dynamics_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"float32 x_vel_target_mps\n"
"float32 y_vel_target_mps\n"
"float32 yaw_rate_target_rps\n"
"float32 linear_actuator_target_m\n"
"float32 x_vel_limit_mps\n"
"float32 y_vel_limit_mps\n"
"float32 yaw_rate_limit_rps\n"
"float32 linear_actuator_vel_limit_mps\n"
"float32[] wheel_vel_mps\n"
"float32[] wheel_pos_m\n"
"float32 linear_actuator_vel_mps\n"
"float32 linear_actuator_position_m\n"
"float32 x_accel_mps2\n"
"float32 y_accel_mps2\n"
"float32 yaw_accel_mps2\n"
"float32 yaw_angle_rad\n"
"float32 odom_yaw_angle_rad\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::movo_msgs::Dynamics_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::movo_msgs::Dynamics_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.x_vel_target_mps);
      stream.next(m.y_vel_target_mps);
      stream.next(m.yaw_rate_target_rps);
      stream.next(m.linear_actuator_target_m);
      stream.next(m.x_vel_limit_mps);
      stream.next(m.y_vel_limit_mps);
      stream.next(m.yaw_rate_limit_rps);
      stream.next(m.linear_actuator_vel_limit_mps);
      stream.next(m.wheel_vel_mps);
      stream.next(m.wheel_pos_m);
      stream.next(m.linear_actuator_vel_mps);
      stream.next(m.linear_actuator_position_m);
      stream.next(m.x_accel_mps2);
      stream.next(m.y_accel_mps2);
      stream.next(m.yaw_accel_mps2);
      stream.next(m.yaw_angle_rad);
      stream.next(m.odom_yaw_angle_rad);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Dynamics_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::movo_msgs::Dynamics_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::movo_msgs::Dynamics_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "header: ";
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "x_vel_target_mps: ";
    Printer<float>::stream(s, indent + "  ", v.x_vel_target_mps);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "y_vel_target_mps: ";
    Printer<float>::stream(s, indent + "  ", v.y_vel_target_mps);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "yaw_rate_target_rps: ";
    Printer<float>::stream(s, indent + "  ", v.yaw_rate_target_rps);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "linear_actuator_target_m: ";
    Printer<float>::stream(s, indent + "  ", v.linear_actuator_target_m);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "x_vel_limit_mps: ";
    Printer<float>::stream(s, indent + "  ", v.x_vel_limit_mps);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "y_vel_limit_mps: ";
    Printer<float>::stream(s, indent + "  ", v.y_vel_limit_mps);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "yaw_rate_limit_rps: ";
    Printer<float>::stream(s, indent + "  ", v.yaw_rate_limit_rps);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "linear_actuator_vel_limit_mps: ";
    Printer<float>::stream(s, indent + "  ", v.linear_actuator_vel_limit_mps);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "wheel_vel_mps: ";
    if (v.wheel_vel_mps.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.wheel_vel_mps.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<float>::stream(s, true ? std::string() : indent + "    ", v.wheel_vel_mps[i]);
    }
    if (v.wheel_vel_mps.empty() || true)
      s << "]";
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "wheel_pos_m: ";
    if (v.wheel_pos_m.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.wheel_pos_m.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<float>::stream(s, true ? std::string() : indent + "    ", v.wheel_pos_m[i]);
    }
    if (v.wheel_pos_m.empty() || true)
      s << "]";
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "linear_actuator_vel_mps: ";
    Printer<float>::stream(s, indent + "  ", v.linear_actuator_vel_mps);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "linear_actuator_position_m: ";
    Printer<float>::stream(s, indent + "  ", v.linear_actuator_position_m);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "x_accel_mps2: ";
    Printer<float>::stream(s, indent + "  ", v.x_accel_mps2);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "y_accel_mps2: ";
    Printer<float>::stream(s, indent + "  ", v.y_accel_mps2);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "yaw_accel_mps2: ";
    Printer<float>::stream(s, indent + "  ", v.yaw_accel_mps2);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "yaw_angle_rad: ";
    Printer<float>::stream(s, indent + "  ", v.yaw_angle_rad);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "odom_yaw_angle_rad: ";
    Printer<float>::stream(s, indent + "  ", v.odom_yaw_angle_rad);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MOVO_MSGS_MESSAGE_DYNAMICS_H
