// Generated by gencpp from file movo_msgs/JacoStatus.msg
// DO NOT EDIT!


#ifndef MOVO_MSGS_MESSAGE_JACOSTATUS_H
#define MOVO_MSGS_MESSAGE_JACOSTATUS_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace movo_msgs
{
template <class ContainerAllocator>
struct JacoStatus_
{
  typedef JacoStatus_<ContainerAllocator> Type;

  JacoStatus_()
    : header()
    , raw_joint_pos_rad()  {
    }
  JacoStatus_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , raw_joint_pos_rad(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector<float, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<float>> _raw_joint_pos_rad_type;
  _raw_joint_pos_rad_type raw_joint_pos_rad;





  typedef boost::shared_ptr< ::movo_msgs::JacoStatus_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::movo_msgs::JacoStatus_<ContainerAllocator> const> ConstPtr;

}; // struct JacoStatus_

typedef ::movo_msgs::JacoStatus_<std::allocator<void> > JacoStatus;

typedef boost::shared_ptr< ::movo_msgs::JacoStatus > JacoStatusPtr;
typedef boost::shared_ptr< ::movo_msgs::JacoStatus const> JacoStatusConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::movo_msgs::JacoStatus_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::movo_msgs::JacoStatus_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::movo_msgs::JacoStatus_<ContainerAllocator1> & lhs, const ::movo_msgs::JacoStatus_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.raw_joint_pos_rad == rhs.raw_joint_pos_rad;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::movo_msgs::JacoStatus_<ContainerAllocator1> & lhs, const ::movo_msgs::JacoStatus_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace movo_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::movo_msgs::JacoStatus_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::movo_msgs::JacoStatus_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::movo_msgs::JacoStatus_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::movo_msgs::JacoStatus_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::movo_msgs::JacoStatus_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::movo_msgs::JacoStatus_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::movo_msgs::JacoStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d7737d010f68dc207c2b507e374ae436";
  }

  static const char* value(const ::movo_msgs::JacoStatus_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd7737d010f68dc20ULL;
  static const uint64_t static_value2 = 0x7c2b507e374ae436ULL;
};

template<class ContainerAllocator>
struct DataType< ::movo_msgs::JacoStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "movo_msgs/JacoStatus";
  }

  static const char* value(const ::movo_msgs::JacoStatus_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::movo_msgs::JacoStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"float32[] raw_joint_pos_rad\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::movo_msgs::JacoStatus_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::movo_msgs::JacoStatus_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.raw_joint_pos_rad);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct JacoStatus_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::movo_msgs::JacoStatus_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::movo_msgs::JacoStatus_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "header: ";
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "raw_joint_pos_rad: ";
    if (v.raw_joint_pos_rad.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.raw_joint_pos_rad.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<float>::stream(s, true ? std::string() : indent + "    ", v.raw_joint_pos_rad[i]);
    }
    if (v.raw_joint_pos_rad.empty() || true)
      s << "]";
  }
};

} // namespace message_operations
} // namespace ros

#endif // MOVO_MSGS_MESSAGE_JACOSTATUS_H
