// Generated by gencpp from file movo_msgs/JacoJointCmd.msg
// DO NOT EDIT!


#ifndef MOVO_MSGS_MESSAGE_JACOJOINTCMD_H
#define MOVO_MSGS_MESSAGE_JACOJOINTCMD_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace movo_msgs
{
template <class ContainerAllocator>
struct JacoJointCmd_
{
  typedef JacoJointCmd_<ContainerAllocator> Type;

  JacoJointCmd_()
    : header()
    , command_type(0)
    , joint_cmds()
    , vel_limits()  {
    }
  JacoJointCmd_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , command_type(0)
    , joint_cmds(_alloc)
    , vel_limits(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint32_t _command_type_type;
  _command_type_type command_type;

   typedef std::vector<float, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<float>> _joint_cmds_type;
  _joint_cmds_type joint_cmds;

   typedef std::vector<float, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<float>> _vel_limits_type;
  _vel_limits_type vel_limits;





  typedef boost::shared_ptr< ::movo_msgs::JacoJointCmd_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::movo_msgs::JacoJointCmd_<ContainerAllocator> const> ConstPtr;

}; // struct JacoJointCmd_

typedef ::movo_msgs::JacoJointCmd_<std::allocator<void> > JacoJointCmd;

typedef boost::shared_ptr< ::movo_msgs::JacoJointCmd > JacoJointCmdPtr;
typedef boost::shared_ptr< ::movo_msgs::JacoJointCmd const> JacoJointCmdConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::movo_msgs::JacoJointCmd_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::movo_msgs::JacoJointCmd_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::movo_msgs::JacoJointCmd_<ContainerAllocator1> & lhs, const ::movo_msgs::JacoJointCmd_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.command_type == rhs.command_type &&
    lhs.joint_cmds == rhs.joint_cmds &&
    lhs.vel_limits == rhs.vel_limits;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::movo_msgs::JacoJointCmd_<ContainerAllocator1> & lhs, const ::movo_msgs::JacoJointCmd_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace movo_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::movo_msgs::JacoJointCmd_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::movo_msgs::JacoJointCmd_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::movo_msgs::JacoJointCmd_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::movo_msgs::JacoJointCmd_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::movo_msgs::JacoJointCmd_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::movo_msgs::JacoJointCmd_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::movo_msgs::JacoJointCmd_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f04ef8268b267f61fee55c68b617df3d";
  }

  static const char* value(const ::movo_msgs::JacoJointCmd_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf04ef8268b267f61ULL;
  static const uint64_t static_value2 = 0xfee55c68b617df3dULL;
};

template<class ContainerAllocator>
struct DataType< ::movo_msgs::JacoJointCmd_<ContainerAllocator> >
{
  static const char* value()
  {
    return "movo_msgs/JacoJointCmd";
  }

  static const char* value(const ::movo_msgs::JacoJointCmd_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::movo_msgs::JacoJointCmd_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"uint32 command_type\n"
"float32[] joint_cmds\n"
"float32[] vel_limits\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::movo_msgs::JacoJointCmd_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::movo_msgs::JacoJointCmd_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.command_type);
      stream.next(m.joint_cmds);
      stream.next(m.vel_limits);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct JacoJointCmd_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::movo_msgs::JacoJointCmd_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::movo_msgs::JacoJointCmd_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "header: ";
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "command_type: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.command_type);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "joint_cmds: ";
    if (v.joint_cmds.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.joint_cmds.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<float>::stream(s, true ? std::string() : indent + "    ", v.joint_cmds[i]);
    }
    if (v.joint_cmds.empty() || true)
      s << "]";
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "vel_limits: ";
    if (v.vel_limits.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.vel_limits.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<float>::stream(s, true ? std::string() : indent + "    ", v.vel_limits[i]);
    }
    if (v.vel_limits.empty() || true)
      s << "]";
  }
};

} // namespace message_operations
} // namespace ros

#endif // MOVO_MSGS_MESSAGE_JACOJOINTCMD_H
