// Generated by gencpp from file movo_msgs/KinovaActuatorFdbk.msg
// DO NOT EDIT!


#ifndef MOVO_MSGS_MESSAGE_KINOVAACTUATORFDBK_H
#define MOVO_MSGS_MESSAGE_KINOVAACTUATORFDBK_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace movo_msgs
{
template <class ContainerAllocator>
struct KinovaActuatorFdbk_
{
  typedef KinovaActuatorFdbk_<ContainerAllocator> Type;

  KinovaActuatorFdbk_()
    : header()
    , current()
    , temperature()  {
    }
  KinovaActuatorFdbk_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , current(_alloc)
    , temperature(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector<float, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<float>> _current_type;
  _current_type current;

   typedef std::vector<float, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<float>> _temperature_type;
  _temperature_type temperature;





  typedef boost::shared_ptr< ::movo_msgs::KinovaActuatorFdbk_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::movo_msgs::KinovaActuatorFdbk_<ContainerAllocator> const> ConstPtr;

}; // struct KinovaActuatorFdbk_

typedef ::movo_msgs::KinovaActuatorFdbk_<std::allocator<void> > KinovaActuatorFdbk;

typedef boost::shared_ptr< ::movo_msgs::KinovaActuatorFdbk > KinovaActuatorFdbkPtr;
typedef boost::shared_ptr< ::movo_msgs::KinovaActuatorFdbk const> KinovaActuatorFdbkConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::movo_msgs::KinovaActuatorFdbk_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::movo_msgs::KinovaActuatorFdbk_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::movo_msgs::KinovaActuatorFdbk_<ContainerAllocator1> & lhs, const ::movo_msgs::KinovaActuatorFdbk_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.current == rhs.current &&
    lhs.temperature == rhs.temperature;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::movo_msgs::KinovaActuatorFdbk_<ContainerAllocator1> & lhs, const ::movo_msgs::KinovaActuatorFdbk_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace movo_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::movo_msgs::KinovaActuatorFdbk_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::movo_msgs::KinovaActuatorFdbk_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::movo_msgs::KinovaActuatorFdbk_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::movo_msgs::KinovaActuatorFdbk_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::movo_msgs::KinovaActuatorFdbk_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::movo_msgs::KinovaActuatorFdbk_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::movo_msgs::KinovaActuatorFdbk_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e4c6d57595be8397a51a210a33d3ba9e";
  }

  static const char* value(const ::movo_msgs::KinovaActuatorFdbk_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe4c6d57595be8397ULL;
  static const uint64_t static_value2 = 0xa51a210a33d3ba9eULL;
};

template<class ContainerAllocator>
struct DataType< ::movo_msgs::KinovaActuatorFdbk_<ContainerAllocator> >
{
  static const char* value()
  {
    return "movo_msgs/KinovaActuatorFdbk";
  }

  static const char* value(const ::movo_msgs::KinovaActuatorFdbk_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::movo_msgs::KinovaActuatorFdbk_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"float32[] current\n"
"float32[] temperature\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::movo_msgs::KinovaActuatorFdbk_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::movo_msgs::KinovaActuatorFdbk_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.current);
      stream.next(m.temperature);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct KinovaActuatorFdbk_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::movo_msgs::KinovaActuatorFdbk_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::movo_msgs::KinovaActuatorFdbk_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "header: ";
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "current: ";
    if (v.current.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.current.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<float>::stream(s, true ? std::string() : indent + "    ", v.current[i]);
    }
    if (v.current.empty() || true)
      s << "]";
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "temperature: ";
    if (v.temperature.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.temperature.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<float>::stream(s, true ? std::string() : indent + "    ", v.temperature[i]);
    }
    if (v.temperature.empty() || true)
      s << "]";
  }
};

} // namespace message_operations
} // namespace ros

#endif // MOVO_MSGS_MESSAGE_KINOVAACTUATORFDBK_H
