// Generated by gencpp from file movo_msgs/Propulsion.msg
// DO NOT EDIT!


#ifndef MOVO_MSGS_MESSAGE_PROPULSION_H
#define MOVO_MSGS_MESSAGE_PROPULSION_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace movo_msgs
{
template <class ContainerAllocator>
struct Propulsion_
{
  typedef Propulsion_<ContainerAllocator> Type;

  Propulsion_()
    : header()
    , wheel_motor_status()
    , wheel_motor_current_A0pk()
    , wheel_motor_speed_rps()
    , wheel_motor_position_rad()
    , linear_motor_status(0)
    , linear_motor_current_A0pk(0.0)
    , linear_motor_speed_rps(0.0)
    , linear_motor_position_rad(0.0)  {
    }
  Propulsion_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , wheel_motor_status(_alloc)
    , wheel_motor_current_A0pk(_alloc)
    , wheel_motor_speed_rps(_alloc)
    , wheel_motor_position_rad(_alloc)
    , linear_motor_status(0)
    , linear_motor_current_A0pk(0.0)
    , linear_motor_speed_rps(0.0)
    , linear_motor_position_rad(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector<uint32_t, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<uint32_t>> _wheel_motor_status_type;
  _wheel_motor_status_type wheel_motor_status;

   typedef std::vector<float, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<float>> _wheel_motor_current_A0pk_type;
  _wheel_motor_current_A0pk_type wheel_motor_current_A0pk;

   typedef std::vector<float, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<float>> _wheel_motor_speed_rps_type;
  _wheel_motor_speed_rps_type wheel_motor_speed_rps;

   typedef std::vector<float, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<float>> _wheel_motor_position_rad_type;
  _wheel_motor_position_rad_type wheel_motor_position_rad;

   typedef uint32_t _linear_motor_status_type;
  _linear_motor_status_type linear_motor_status;

   typedef float _linear_motor_current_A0pk_type;
  _linear_motor_current_A0pk_type linear_motor_current_A0pk;

   typedef float _linear_motor_speed_rps_type;
  _linear_motor_speed_rps_type linear_motor_speed_rps;

   typedef float _linear_motor_position_rad_type;
  _linear_motor_position_rad_type linear_motor_position_rad;





  typedef boost::shared_ptr< ::movo_msgs::Propulsion_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::movo_msgs::Propulsion_<ContainerAllocator> const> ConstPtr;

}; // struct Propulsion_

typedef ::movo_msgs::Propulsion_<std::allocator<void> > Propulsion;

typedef boost::shared_ptr< ::movo_msgs::Propulsion > PropulsionPtr;
typedef boost::shared_ptr< ::movo_msgs::Propulsion const> PropulsionConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::movo_msgs::Propulsion_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::movo_msgs::Propulsion_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::movo_msgs::Propulsion_<ContainerAllocator1> & lhs, const ::movo_msgs::Propulsion_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.wheel_motor_status == rhs.wheel_motor_status &&
    lhs.wheel_motor_current_A0pk == rhs.wheel_motor_current_A0pk &&
    lhs.wheel_motor_speed_rps == rhs.wheel_motor_speed_rps &&
    lhs.wheel_motor_position_rad == rhs.wheel_motor_position_rad &&
    lhs.linear_motor_status == rhs.linear_motor_status &&
    lhs.linear_motor_current_A0pk == rhs.linear_motor_current_A0pk &&
    lhs.linear_motor_speed_rps == rhs.linear_motor_speed_rps &&
    lhs.linear_motor_position_rad == rhs.linear_motor_position_rad;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::movo_msgs::Propulsion_<ContainerAllocator1> & lhs, const ::movo_msgs::Propulsion_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace movo_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::movo_msgs::Propulsion_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::movo_msgs::Propulsion_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::movo_msgs::Propulsion_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::movo_msgs::Propulsion_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::movo_msgs::Propulsion_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::movo_msgs::Propulsion_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::movo_msgs::Propulsion_<ContainerAllocator> >
{
  static const char* value()
  {
    return "61491c2b54c7a9e181eff35f997fd6b8";
  }

  static const char* value(const ::movo_msgs::Propulsion_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x61491c2b54c7a9e1ULL;
  static const uint64_t static_value2 = 0x81eff35f997fd6b8ULL;
};

template<class ContainerAllocator>
struct DataType< ::movo_msgs::Propulsion_<ContainerAllocator> >
{
  static const char* value()
  {
    return "movo_msgs/Propulsion";
  }

  static const char* value(const ::movo_msgs::Propulsion_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::movo_msgs::Propulsion_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"uint32[] wheel_motor_status\n"
"float32[] wheel_motor_current_A0pk\n"
"float32[] wheel_motor_speed_rps\n"
"float32[] wheel_motor_position_rad\n"
"uint32 linear_motor_status\n"
"float32 linear_motor_current_A0pk\n"
"float32 linear_motor_speed_rps\n"
"float32 linear_motor_position_rad\n"
" \n"
"\n"
"\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::movo_msgs::Propulsion_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::movo_msgs::Propulsion_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.wheel_motor_status);
      stream.next(m.wheel_motor_current_A0pk);
      stream.next(m.wheel_motor_speed_rps);
      stream.next(m.wheel_motor_position_rad);
      stream.next(m.linear_motor_status);
      stream.next(m.linear_motor_current_A0pk);
      stream.next(m.linear_motor_speed_rps);
      stream.next(m.linear_motor_position_rad);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Propulsion_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::movo_msgs::Propulsion_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::movo_msgs::Propulsion_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "header: ";
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "wheel_motor_status: ";
    if (v.wheel_motor_status.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.wheel_motor_status.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<uint32_t>::stream(s, true ? std::string() : indent + "    ", v.wheel_motor_status[i]);
    }
    if (v.wheel_motor_status.empty() || true)
      s << "]";
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "wheel_motor_current_A0pk: ";
    if (v.wheel_motor_current_A0pk.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.wheel_motor_current_A0pk.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<float>::stream(s, true ? std::string() : indent + "    ", v.wheel_motor_current_A0pk[i]);
    }
    if (v.wheel_motor_current_A0pk.empty() || true)
      s << "]";
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "wheel_motor_speed_rps: ";
    if (v.wheel_motor_speed_rps.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.wheel_motor_speed_rps.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<float>::stream(s, true ? std::string() : indent + "    ", v.wheel_motor_speed_rps[i]);
    }
    if (v.wheel_motor_speed_rps.empty() || true)
      s << "]";
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "wheel_motor_position_rad: ";
    if (v.wheel_motor_position_rad.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.wheel_motor_position_rad.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<float>::stream(s, true ? std::string() : indent + "    ", v.wheel_motor_position_rad[i]);
    }
    if (v.wheel_motor_position_rad.empty() || true)
      s << "]";
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "linear_motor_status: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.linear_motor_status);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "linear_motor_current_A0pk: ";
    Printer<float>::stream(s, indent + "  ", v.linear_motor_current_A0pk);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "linear_motor_speed_rps: ";
    Printer<float>::stream(s, indent + "  ", v.linear_motor_speed_rps);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "linear_motor_position_rad: ";
    Printer<float>::stream(s, indent + "  ", v.linear_motor_position_rad);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MOVO_MSGS_MESSAGE_PROPULSION_H
