// Generated by gencpp from file movo_msgs/Status.msg
// DO NOT EDIT!


#ifndef MOVO_MSGS_MESSAGE_STATUS_H
#define MOVO_MSGS_MESSAGE_STATUS_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace movo_msgs
{
template <class ContainerAllocator>
struct Status_
{
  typedef Status_<ContainerAllocator> Type;

  Status_()
    : header()
    , fault_status_words()
    , operational_time(0.0)
    , operational_state(0)
    , dynamic_response(0)
    , machine_id(0)  {
    }
  Status_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , fault_status_words(_alloc)
    , operational_time(0.0)
    , operational_state(0)
    , dynamic_response(0)
    , machine_id(0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector<uint32_t, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<uint32_t>> _fault_status_words_type;
  _fault_status_words_type fault_status_words;

   typedef float _operational_time_type;
  _operational_time_type operational_time;

   typedef uint32_t _operational_state_type;
  _operational_state_type operational_state;

   typedef uint32_t _dynamic_response_type;
  _dynamic_response_type dynamic_response;

   typedef uint32_t _machine_id_type;
  _machine_id_type machine_id;





  typedef boost::shared_ptr< ::movo_msgs::Status_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::movo_msgs::Status_<ContainerAllocator> const> ConstPtr;

}; // struct Status_

typedef ::movo_msgs::Status_<std::allocator<void> > Status;

typedef boost::shared_ptr< ::movo_msgs::Status > StatusPtr;
typedef boost::shared_ptr< ::movo_msgs::Status const> StatusConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::movo_msgs::Status_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::movo_msgs::Status_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::movo_msgs::Status_<ContainerAllocator1> & lhs, const ::movo_msgs::Status_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.fault_status_words == rhs.fault_status_words &&
    lhs.operational_time == rhs.operational_time &&
    lhs.operational_state == rhs.operational_state &&
    lhs.dynamic_response == rhs.dynamic_response &&
    lhs.machine_id == rhs.machine_id;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::movo_msgs::Status_<ContainerAllocator1> & lhs, const ::movo_msgs::Status_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace movo_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::movo_msgs::Status_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::movo_msgs::Status_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::movo_msgs::Status_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::movo_msgs::Status_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::movo_msgs::Status_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::movo_msgs::Status_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::movo_msgs::Status_<ContainerAllocator> >
{
  static const char* value()
  {
    return "dde32396dda94858b879d71dd7ee2e6c";
  }

  static const char* value(const ::movo_msgs::Status_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xdde32396dda94858ULL;
  static const uint64_t static_value2 = 0xb879d71dd7ee2e6cULL;
};

template<class ContainerAllocator>
struct DataType< ::movo_msgs::Status_<ContainerAllocator> >
{
  static const char* value()
  {
    return "movo_msgs/Status";
  }

  static const char* value(const ::movo_msgs::Status_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::movo_msgs::Status_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"uint32[] fault_status_words\n"
"float32 operational_time\n"
"uint32 operational_state\n"
"uint32 dynamic_response\n"
"uint32 machine_id\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::movo_msgs::Status_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::movo_msgs::Status_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.fault_status_words);
      stream.next(m.operational_time);
      stream.next(m.operational_state);
      stream.next(m.dynamic_response);
      stream.next(m.machine_id);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Status_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::movo_msgs::Status_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::movo_msgs::Status_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "header: ";
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "fault_status_words: ";
    if (v.fault_status_words.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.fault_status_words.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<uint32_t>::stream(s, true ? std::string() : indent + "    ", v.fault_status_words[i]);
    }
    if (v.fault_status_words.empty() || true)
      s << "]";
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "operational_time: ";
    Printer<float>::stream(s, indent + "  ", v.operational_time);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "operational_state: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.operational_state);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "dynamic_response: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.dynamic_response);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "machine_id: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.machine_id);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MOVO_MSGS_MESSAGE_STATUS_H
